Update example for __setting entity annotations__
On the documentation page for [linguistic feature](https://github.com/explosion/spaCy/blob/master/website/docs/usage/linguistic-features.md), in the section __Setting entity annotations__, the example uses "FB" as an unrecognized entity that needs to be set in the doc. However, it seems that with the `en_core_web_sm` model, FB is now recognized as an entity, therefore breaking the example. 

Output with the error:
```
Before [('FB', 0, 2, 'ORG')]
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-1-5dfcd9e76b96> in <module>
      9 
     10 fb_ent = Span(doc, 0, 1, label="ORG") # create a Span for the new entity
---> 11 doc.ents = list(doc.ents) + [fb_ent]
     12 
     13 ents = [(e.text, e.start_char, e.end_char, e.label_) for e in doc.ents]

doc.pyx in spacy.tokens.doc.Doc.ents.__set__()

ValueError: [E103] Trying to set conflicting doc.ents: '(0, 1, 'ORG')' and '(0, 1, 'ORG')'. A token can only be part of one entity, so make sure the entities you're setting don't overlap.
```

There needs to be another commonly used symbol for a company that does not get correctly tagged by the small model. "AAPL" is sometimes used for Apple Inc. but does not get tagged by the small model.