the default example for "Setting entity annotations" errors on Binder
To the uninitiated, the example at https://spacy.io/usage/linguistic-features#setting-entities
errors on Binder because the code tries to set the entity for "fb" twice.
The exact error as reported is -
```
ValueError                                Traceback (most recent call last)
<ipython-input-1-73c2a9e8d913> in <module>
     15
     16 # Option 2: Assign a complete list of ents to doc.ents
---> 17 doc.ents = list(doc.ents) + [fb_ent]
     18
     19 ents = [(e.text, e.start, e.end, e.label_) for e in doc.ents]

/srv/conda/envs/notebook/lib/python3.7/site-packages/spacy/tokens/doc.pyx in spacy.tokens.doc.Doc.ents.__set__()

/srv/conda/envs/notebook/lib/python3.7/site-packages/spacy/tokens/doc.pyx in spacy.tokens.doc.Doc.set_ents()

ValueError: [E1010] Unable to set entity information for token 0 which is included in more than one span in entities, blocked, missing or outside.
```

People short on time or coming here the first time or just beginners may assume that this is
a shortcoming of the library when they are supposed to actually try one of the two options.

So I have commented Option 2 by default, and added a comment adjacent to it stating that
comment option 1 before running option 2.